;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #002e3440
background-alt = #3b4252
foreground = #eceff4
primary = #5e81ac
secondary = #81a1c1
alert = #bf616a
disabled = #4c566a

[bar/top]
width = 100%
height = 20pt
radius = 0

; dpi = 85

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 2pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = Ubuntu Nerd Font:size=11:weight=bold;2

modules-left = icon groups title
modules-center = date weather
modules-right = temperature network update battery capslock tray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

override-redirect = false

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html

; left
[module/icon]
type = custom/text
label = 󰣇

[module/groups]
type = internal/xworkspaces
enable-scroll = false

label-active-underline = ${colors.primary}

label-active = %name%
label-occupied = %name%
label-urgent = %name%
label-empty = %name%

label-active-padding = 1
label-occupied-padding = 1
label-urgent-padding = 1
label-empty-padding = 1

label-urgent-foreground = ${colors.alert}
label-empty-foreground = ${colors.background-alt}

label-active-background = #804c566a
label-occupied-background = ${colors.background}
label-urgent-background = ${colors.background}
label-empty-background = ${colors.background}

[module/title]
type = internal/xwindow
label-empty = Desktop
label-maxlen = 70

; center
[module/date]
type = internal/date
time = %I:%M %p
label = %time%

; dont heed tail here, we update this script every half an hour thats fine
[module/weather]
type = custom/script
exec = python -u .config/polybar/weather.py
interval = 1800

; right
[module/temperature]
type = internal/temperature
format = <label>
format-warn = <label-warn>
label-warn-foreground = ${colors.alert}

[module/network]
type = internal/network
interface-type = wireless
format-connected =  <label-connected>
label-connected = %netspeed%
label-disconnected = unconnected

[module/update]
type = custom/script
exec = python -u .config/polybar/update.py
interval = 300
click-left = konsole -e sudo pacman -Syu

[module/battery]
type = custom/script
exec = python -u .config/polybar/battery.py
tail = true
click-left = blueman-manager &

[module/capslock]
type = internal/xkeyboard
blacklist-0 = num lock
format = <label-indicator>
label-indicator-on = 󰪛
label-indicator-off = 

[module/tray]
type = internal/tray

[bar/bottom]
width = 100%
height = 20pt
radius = 0

; dpi = 85

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 2pt
border-color = #00000000

padding-left = 1
padding-right = 1

font-0 = Ubuntu Nerd Font:size=11:weight=bold;2

modules-center = taskbar music prev toggle next

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

bottom = true
override-redirect = false
wm-restack = generic

; left
[module/taskbar]
type = custom/script
exec = python -u .config/polybar/taskbar.py
tail = true

; right
[module/music]
type = custom/script
exec = python -u .config/polybar/music.py
tail = true
format-padding = 1

[module/prev]
type = custom/text
label = 
format-padding = 1
click-left = playerctl previous

[module/toggle]
type = custom/script
exec = python -u .config/polybar/toggle.py
tail = true
format-padding = 1
click-left = playerctl play-pause

[module/next]
type = custom/text
label = 
format-padding = 1
click-left = playerctl next

; vim:ft=dosini
